apiVersion: v1
kind: ConfigMap
metadata:
  name: rrhh-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "dpg-d8io5gt8nd3s73dq80ag-a.ohio-postgres.render.com"
  DB_PORT: "5432"
  DB_NAME: "rrhh_db_74e6"
  DB_USERNAME: "abel"
  SERVER_PORT: "8080"
  LOG_LEVEL: "INFO"
  
  # ══ CORS ══
  CORS_ALLOWED_ORIGINS: "*"
  
  # ══ GRAPHQL ══
  GRAPHIQL_ENABLED: "false"
  GRAPHQL_PATH: "/graphql"
  
  # ══ AWS (No sensibles) ══
  AWS_ENABLED: "true"
  AWS_REGION: "us-east-2"
  AWS_S3_BUCKET: "amazon-s3-bucket-v001"
  DYNAMODB_TABLE_AUDITORIA: "rrhh_bitacora"
  
  # ══ FIREBASE FCM ══
  FCM_ENABLED: "false"
  FCM_PROJECT_ID: "rrhh-project"
  # NOTA: FCM_CREDENTIALS_PATH requerirá que subas el archivo .json al servidor
  
  # ══ BLOCKCHAIN (No sensibles) ══
  BLOCKCHAIN_RPC_URL: "https://polygon-amoy.g.alchemy.com/v2/2qKAvdBA62wytNZnFUQ56"
  BLOCKCHAIN_CONTRACT_ADDRESS: "0xe31619a072e4cC63Daf12BE47F49F3Dd890717B1"
  BLOCKCHAIN_CHAIN_ID: "80002"
