apiVersion: v1
kind: Secret
metadata:
  name: rrhh-secret
type: Opaque
stringData:
  # ══ BASE DE DATOS Y JWT ══
  DB_PASSWORD: "tu_password_de_render_aqui"
  JWT_SECRET: "bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uU3lzdGVtMjAyNQ=="
  
  # ══ AWS CREDENCIALES (Reemplazar en AWS) ══
  AWS_ACCESS_KEY_ID: "tu_access_key_aqui"
  AWS_SECRET_ACCESS_KEY: "tu_secret_key_aqui"
  
  # ══ BLOCKCHAIN (Reemplazar en AWS) ══
  BLOCKCHAIN_PRIVATE_KEY: "tu_private_key_de_metamask_aqui"
